---
title: "About"
---

<link rel="stylesheet" href="styles.css" type="text/css">

I am a bio-statistician currently working as Senior Strategic Information Advisor, previously worked as independent consultant; M&E advisor on international non-governmental organization in Mozambique, focused on continuous quality improvement (CQI), supporting internal Data Quality Assessments (iDQA) by implementing partners, including provision of technical assistance to MOH in country, development and delivery of training materials, coordinating and alignment of the Global Programs activities through an M&E lens, and ongoing capacity building and mentorship for MOH and partner staff. Previously I worked as a voluntary medical male circumcision (VMMC) project manager and data analyst and as a database manager at International Training and Education Center for Health (I-TECH) Mozambique Office. I have skills on development and maintenance of a system of monitoring & evaluation and operational research effective and updated, ensuring the implementation of programs/ projects, with design for data entry screen including the development of tools for data collection for operational research, data analysis and reporting of research
